name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux, windows, mac ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Run GUT tests
        uses: josephbmanley/run-gut-tests-action@v1.1.0

      - name: Decide debugMode
        uses: haya14busa/action-cond@v1
        id: debugMode
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "true"
          if_false: "false"

      - name: Build game client
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: NeoMori
          preset: ${{ matrix.platform }}
          debugMode: ${{ steps.debugMode.outputs.value }}

      - name: Git describe
        run: echo "GIT_DESCRIBE=$(git describe)" >> $GITHUB_ENV

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: NeoMori_${{ github.sha }}_${{ matrix.platform }}
          path: ${{ github.workspace }}/build/*

      - name: Create override.cfg
        if: ${{ env.GIT_DESCRIBE != '' }}
        run: echo "global/version = \"$GIT_DESCRIBE\"" >> override.cfg

      - name: Upload override.cfg
        if: ${{ env.GIT_DESCRIBE != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: NeoMori_${{ github.sha }}_${{ matrix.platform }}
          path: ${{ github.workspace }}/override.cfg
