name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux, windows, mac ]

    steps:
    - name: Download client
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        commit: ${{ github.sha }}
        event: push
        name: NeoMori_${{ github.sha }}_${{ matrix.platform }}
        path: NeoMori

    - name: Update global/version in override.cfg
      run: sed -i "s#global/version\s*=.*#global/version=\"${GITHUB_REF/refs\/tags\//}\"#g" NeoMori/override.cfg

    - name: Set filename
      run: echo "FILENAME=NeoMori-${GITHUB_REF/refs\/tags\//}-${{ matrix.platform }}" >> $GITHUB_ENV

    - name: Zip client
      run: zip -q -r ${{ env.FILENAME }}.zip NeoMori

    - name: Publish to github release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.FILENAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to itch.io
      uses: josephbmanley/butler-publish-itchio-action@v1.0.2
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: ${{ matrix.platform }}
        ITCH_GAME: neomori
        ITCH_USER: eficode
        PACKAGE: ${{ env.FILENAME }}.zip
        VERSION: ${GITHUB_REF/refs\/tags\//}

