name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Download pre-built clients
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Build
        workflow_conclusion: success
        commit: ${{ env.GITHUB_SHA }}

    - name: Publish clients
      uses: softprops/action-gh-release@v1
      with:
        files: '*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
