name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Add version number using semantic versioning, e.g. '0.1.2'"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.event.inputs.tag }}"
