name: tollgate

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: NeoMori
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - uses: josephbmanley/run-gut-tests-action@v1.1.0
      - name: Get git describe version
        run: echo "GIT_DESCRIBE=$(git describe)" >> $GITHUB_ENV
      - name: Create override.cfg
        run: sudo echo "version = $GIT_DESCRIBE" > ${{ github.workspace }}/build/override.cfg
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/build/* 
